import type { Question } from '../data'

const REFERENCE = 'Original hard practice · APSLPRB Paper I / SSC CGL aptitude syllabus alignment'

const hard = (
  id: string,
  subject: 'Arithmetic' | 'Reasoning',
  topic: string,
  question: string,
  options: string[],
  answer: number,
  explanation: string,
  hint: string,
  seconds: number,
): Question => ({ id, subject, topic, question, options, answer, explanation, hint, seconds, difficulty: 'Hard', source: REFERENCE })

/**
 * Original high-difficulty items. The coverage follows the published Paper I
 * arithmetic/mental-ability pattern and the comparable SSC graduate-level
 * aptitude syllabus; wording and numerical constructions are editorial.
 */
export const hardQuantReasoningQuestions: Question[] = [
  hard('hqa001','Arithmetic','Number system','What is the least positive integer greater than 50 which leaves remainders 5, 9 and 17 when divided by 12, 16 and 24 respectively?',['89','113','137','185'],0,'The three conditions are all n ≡ −7. Thus n+7 must be a multiple of LCM(12,16,24)=48. The least such value above 50 is 48×2−7=89.','Rewrite every remainder as divisor minus the same number.',105),
  hard('hqa002','Arithmetic','Remainders','What is the remainder when 7¹⁰³ + 3¹⁰³ is divided by 10?',['0','2','4','6'],0,'The last digits of powers of 7 cycle 7,9,3,1; 103 ≡ 3 (mod 4), so 7¹⁰³ ends in 3. Powers of 3 cycle 3,9,7,1; 103 ≡ 3, so 3¹⁰³ ends in 7. Their sum ends in 0.','Use the four-term last-digit cycles.',75),
  hard('hqa003','Arithmetic','HCF and LCM','Two numbers have HCF 18 and LCM 756. If one number is 126, what is the other?',['90','96','108','126'],2,'For two positive integers, product = HCF×LCM. The other number is 18×756÷126 = 108.','Use product of numbers = HCF × LCM.',65),
  hard('hqa004','Arithmetic','Percentages','A value is increased by x% and then decreased by (x−10)%. The final value is 8% above the original. Find x.',['20%','25%','30%','35%'],0,'(1+x/100)(1−(x−10)/100)=1.08. Multiplying by 10000 gives (100+x)(110−x)=10800, so x²−10x−200=0. The positive root is x=20.','Translate the two changes into multipliers.',110),
  hard('hqa005','Arithmetic','Ratio and proportion','A vessel contains milk and water in the ratio 7:5. When 12 litres of mixture are removed and replaced by water, the ratio becomes 7:9. What was the original volume?',['36 L','42 L','48 L','56 L'],2,'Let volume be V. Milk after withdrawal is (7/12)(V−12), while total volume stays V. The final milk fraction is 7/16. Hence (7/12)(V−12)=7V/16. Cancelling 7 and solving gives 4(V−12)=3V, so V=48 litres.','Track the milk fraction; replacement adds no milk.',120),
  hard('hqa006','Arithmetic','Average','The average of 20 observations is 35. The average of the first 12 is 32, and that of the last 9 is 39. What is the 12th observation?',['31','33','35','37'],2,'The first 12 and last 9 contain 21 entries because the 12th is counted twice. Their totals add to 12×32+9×39=735. The total of all 20 is 700, so the repeated 12th observation is 735−700=35.','The overlapping observation is counted twice.',75),
  hard('hqa007','Arithmetic','Profit and loss','A trader marks goods 40% above cost. He gives a 10% discount and uses a 900 g weight as 1 kg. What is his actual profit percentage?',['36%','40%','44%','48%'],1,'For 900 g costing ₹90 when the true cost is ₹100/kg, the billed price for “1 kg” is 100×1.4×0.9=₹126. Profit is 126−90=₹36 on ₹90, or 40%.','Compare billed revenue with the cost of only 900 g.',100),
  hard('hqa008','Arithmetic','Compound interest','A sum amounts to ₹13,310 in 3 years and ₹14,641 in 4 years at annual compound interest. Find the principal.',['₹9,000','₹10,000','₹11,000','₹12,100'],1,'The one-year growth factor is 14641/13310=1.10, so the rate is 10%. Principal = 13310/(1.1)³ = 13310/1.331 = ₹10,000.','First obtain the annual multiplier from consecutive amounts.',90),
  hard('hqa009','Arithmetic','Time and work','A and B together finish a job in 12 days, B and C in 15 days, and C and A in 20 days. In how many days can A alone finish it?',['24','30','40','60'],1,'Let daily rates be a,b,c. Then a+b=1/12, b+c=1/15, c+a=1/20. Adding the first and third and subtracting the second gives 2a=1/12+1/20−1/15=1/15, so a=1/30.','Combine the pair rates to isolate A.',100),
  hard('hqa010','Arithmetic','Pipes and cisterns','Pipe A fills a tank in 12 hours and B in 18 hours. A leak can empty a full tank in 36 hours. A and the leak are opened first; B is opened 4 hours later. How long after B is opened will the tank fill?',['4 hours','5 hours','6 hours','7 hours'],3,'For the first 4 hours, net rate is 1/12−1/36=1/18, filling 2/9. Thereafter net rate is 1/12+1/18−1/36=1/9. The remaining 7/9 takes 7 hours.','Find the amount filled in the first phase, then use the new net rate.',100),
  hard('hqa011','Arithmetic','Trains','A 180 m train crosses a man walking at 6 km/h in the same direction in 12 seconds. How long will it take the train to cross a 270 m platform?',['24 s','25 s','27 s','30 s'],2,'Relative speed with the man is 180/12=15 m/s. The man walks at 5/3 m/s, so train speed is 50/3 m/s. To clear the platform it covers 180+270=450 m, taking 450÷(50/3)=27 seconds.','Recover train speed from relative speed, then use total length.',125),
  hard('hqa012','Arithmetic','Boats and streams','A boat covers 30 km downstream and 18 km upstream in 4 hours. It also covers 45 km downstream and 18 km upstream in 5 hours. What is its speed in still water?',['10 km/h','12 km/h','15 km/h','18 km/h'],1,'Subtracting the two time equations shows that 15 km downstream takes 1 hour, so downstream speed is 15 km/h. Then 30/15+18/u=4 gives upstream speed u=9 km/h. Still-water speed is (15+9)/2=12 km/h.','Subtract the two journey equations to get downstream speed first.',150),
  hard('hqa013','Arithmetic','Ages','Eight years ago, a mother was four times as old as her daughter. Eight years hence, the mother will be twice the daughter’s age plus 4 years. What is the daughter’s present age?',['12','14','16','18'],3,'Let present ages be M and D. M−8=4(D−8), so M=4D−24. Also M+8=2(D+8)+4, so M=2D+12. Equating gives 2D=36, hence D=18.','Form one equation for each stated time.',100),
  hard('hqa014','Arithmetic','Partnership','A invests ₹48,000. After 4 months he withdraws one-fourth. B invests ₹60,000 and after 6 months adds ₹20,000. If the annual profit is ₹44,000, what is B’s share?',['₹24,000','₹26,000','₹28,000','₹30,000'],2,'A’s money-months = 48000×4+36000×8=480000. B’s = 60000×6+80000×6=840000. Ratio A:B=4:7, so B receives 7/11×44000=₹28,000.','Compute capital × time separately for each phase.',120),
  hard('hqa015','Arithmetic','Mixtures','A 60-litre solution is 30% acid. How many litres must be removed and replaced by 50% acid solution so that the final mixture is 40% acid?',['15 L','20 L','25 L','30 L'],3,'If x litres are replaced, acid becomes 18−0.3x+0.5x=18+0.2x. Set this equal to 40% of 60, or 24. Then 0.2x=6 and x=30 litres.','Account for acid removed and acid added.',95),
  hard('hqa016','Arithmetic','Algebra','If x + 1/x = 3, find x⁵ + 1/x⁵.',['99','108','123','135'],2,'Let Sₙ=xⁿ+x⁻ⁿ. Then S₀=2, S₁=3 and Sₙ=3Sₙ₋₁−Sₙ₋₂. Thus S₂=7, S₃=18, S₄=47 and S₅=123.','Use the recurrence generated by multiplying by x+1/x.',110),
  hard('hqa017','Arithmetic','Surds','If √(x+9) − √x = 1, find x.',['9','12','16','20'],2,'√(x+9)=√x+1. Squaring gives x+9=x+1+2√x, so √x=4 and x=16.','Isolate one radical, square, then verify.',75),
  hard('hqa018','Arithmetic','Geometry','In a right triangle, the altitude to the hypotenuse divides the hypotenuse into segments of 9 cm and 16 cm. What is the altitude?',['10 cm','12 cm','13 cm','15 cm'],1,'For the altitude h to the hypotenuse, h² equals the product of the two segments: h²=9×16=144. Hence h=12 cm.','Use the geometric-mean theorem.',70),
  hard('hqa019','Arithmetic','Mensuration','A solid sphere of radius 6 cm is melted into identical cones, each of radius 3 cm and height 8 cm. How many cones are formed?',['8','10','12','16'],2,'Sphere volume = (4/3)π×6³=288π. One cone has volume (1/3)π×3²×8=24π. The number is 288π/24π=12.','Equate total volumes.',75),
  hard('hqa020','Arithmetic','Trigonometry','From a point on level ground, the angle of elevation of a tower is 30°. After moving 40 m toward the tower, it becomes 60°. Find the tower’s height.',['10√3 m','20√3 m','30√3 m','40√3 m'],1,'Let the nearer distance be x and height h. Then h=x√3. At the original point, h=(x+40)/√3. Hence 3x=x+40, so x=20 and h=20√3 m.','Use tangent at the two observation points.',100),
  hard('hqa021','Arithmetic','Probability','Two cards are drawn without replacement from a standard 52-card deck. What is the probability that both are face cards?',['11/221','3/52','9/221','1/17'],0,'There are 12 face cards. Probability = 12/52×11/51 = 11/221 after simplification.','Count J, Q and K in all four suits.',75),
  hard('hqa022','Arithmetic','Permutation and combination','How many six-digit numbers can be formed using 0,1,2,3,4,5 without repetition and divisible by 5?',['192','204','216','240'],2,'Ending in 0 gives 5!=120 numbers. Ending in 5 requires the first digit to be one of 1–4 (4 choices), with the remaining four positions arranged in 4!=24 ways, giving 96. Total 216.','Split by final digit 0 or 5, and exclude a leading zero.',100),
  hard('hqa023','Arithmetic','Data interpretation','A firm’s revenue rose 20% in year 1, fell 10% in year 2, and rose 25% in year 3. If year-3 revenue was ₹13.5 crore, what was the initial revenue?',['₹8 crore','₹9 crore','₹10 crore','₹12 crore'],2,'Combined multiplier = 1.2×0.9×1.25=1.35. Initial revenue = 13.5/1.35 = ₹10 crore.','Multiply successive growth factors.',65),
  hard('hqa024','Arithmetic','Clocks','Between 7 and 8 o’clock, when are the hands exactly opposite?',['7:05 5/11','7:10 10/11','7:21 9/11','7:38 2/11'],0,'At m minutes past 7, the separation is |210−5.5m|. Setting it to 180 gives 210−5.5m=180 for the early occurrence, so m=30/5.5=60/11=5 5/11 minutes.','Use hour angle 210+0.5m and minute angle 6m.',115),

  hard('hqr001','Reasoning','Number series','Find the missing term: 4, 10, 24, 54, 116, ?',['226','232','240','242'],3,'Each term is twice the previous term plus consecutive even numbers: 4×2+2=10, 10×2+4=24, 24×2+6=54, 54×2+8=116. Next is 116×2+10=242.','Test multiplication by 2 with a changing addition.',70),
  hard('hqr002','Reasoning','Number series','Find the next term: 2, 5, 16, 65, 326, ?',['1631','1957','1959','2282'],1,'Successive rules are ×2+1, ×3+1, ×4+1, ×5+1. The next is ×6+1: 326×6+1=1957.','Look for a changing multiplier.',65),
  hard('hqr003','Reasoning','Alphabet series','Find the next pair: AZ, CX, FU, JQ, ?',['OL','PM','PK','NM'],0,'First letters move +2,+3,+4, so next +5 gives O. Second letters move −2,−3,−4, so next −5 gives L.','Track the two letters as separate series.',65),
  hard('hqr004','Reasoning','Coding-decoding','In a code, each consonant is replaced by the next consonant and each vowel by the previous vowel in the cyclic order A-E-I-O-U-A. How is POLICE coded?',['QIMEDA','QUMOQF','QUHODF','RUHODG'],0,'P→Q, O→I (previous vowel), L→M, I→E, C→D and E→A, giving QIMEDA.','Apply the consonant and vowel rules independently.',90),
  hard('hqr005','Reasoning','Blood relations','Introducing a man, Tara said, “His wife is the only daughter of my mother’s mother.” Tara’s mother has no sister. How is the man related to Tara?',['Brother','Father','Maternal uncle','Brother-in-law'],1,'Tara’s mother’s mother is her maternal grandmother. That grandmother’s only daughter must be Tara’s mother because Tara’s mother has no sister. The man is the husband of Tara’s mother, hence Tara’s father.','Resolve “only daughter” before identifying her husband.',75),
  hard('hqr006','Reasoning','Directions','Arun walks 12 m north, turns right and walks 5 m, turns right and walks 4 m, then turns left and walks 10 m. How far and in which direction is he from the start?',['15 m east','17 m north-east','17 m south-east','19 m north-east'],1,'His final coordinates are 15 m east and 8 m north. Distance = √(15²+8²)=17 m, and the direction is north-east.','Use coordinates for each leg.',85),
  hard('hqr007','Reasoning','Ranking','In a row, P is 18th from the left and Q is 24th from the right. After they exchange positions, P becomes 31st from the left. How many people are in the row?',['52','53','54','55'],2,'After exchange, P occupies Q’s original position, which is 31st from the left and 24th from the right. Total = 31+24−1=54.','Use the two ranks of Q’s original position.',65),
  hard('hqr008','Reasoning','Syllogism','Statements: All judges are readers. Some readers are poets. No poet is careless. Conclusions: I. Some judges are not careless. II. Some readers are not careless. III. No judge is a poet.',['Only I','Only II','Only II and III','None'],1,'The readers who are poets are not careless, so some readers are not careless: II follows. Nothing forces any judge to be among those poets, so I and III do not follow.','Preserve the “some poets” group through the negative rule.',90),
  hard('hqr009','Reasoning','Syllogism','Statements: Some A are B. All B are C. No C is D. Conclusions: I. Some A are C. II. Some A are not D. III. No B is D.',['Only I and II','Only II and III','All three','Only I and III'],2,'The “some A” that are B must be C, so I follows. Since no C is D, those A are not D, giving II. All B are C and no C is D, so no B is D: III follows.','Carry the same existential members through both universal rules.',95),
  hard('hqr010','Reasoning','Statement and assumption','Statement: “To reduce delays, submit the verification form online before visiting the office,” says a notice. Assumptions: I. Online submission can occur before an office visit. II. Every delay is caused only by paper forms.',['Only I is implicit','Only II is implicit','Both are implicit','Neither is implicit'],0,'The instruction depends on online submission being available before the visit, so I is implicit. It proposes a way to reduce delays but does not claim paper forms are the sole cause, so II is not implicit.','An assumption must be necessary for the advice to make sense.',80),
  hard('hqr011','Reasoning','Statement and course of action','A district finds that many emergency calls fail because callers cannot describe their location. Courses: I. Train call-takers to request nearby landmarks. II. Disable calls that do not include a postal address.',['Only I follows','Only II follows','Both follow','Neither follows'],0,'Requesting landmarks is practical and directly addresses missing location detail. Disabling such calls worsens the emergency risk and is not a reasonable course.','Test relevance and proportionality.',65),
  hard('hqr012','Reasoning','Data sufficiency','What is the two-digit number N? I. The sum of its digits is 11. II. Reversing its digits decreases it by 27.',['I alone sufficient','II alone sufficient','Both together sufficient','Even both are insufficient'],2,'Let N=10a+b. II gives 10a+b−(10b+a)=27, so a−b=3. With I, a+b=11, yielding a=7 and b=4; N=74. Both together are sufficient.','Translate reversal into 10a+b and 10b+a.',100),
  hard('hqr013','Reasoning','Seating arrangement','Six people A, B, C, D, E and F sit in a row facing north. C is immediately right of A. B is second left of C. D is immediately left of E. F is not at an end. If E is at the right end, who sits third from the left?',['A','C','D','F'],1,'E is sixth, so D is fifth. The block B-A-C must occupy positions 1-2-3 or 2-3-4. F cannot be at an end. The first placement forces F into position 4 and is valid, making position 3 C; the second leaves F at position 1, an end, invalid. Thus C is third.','Treat B-A-C and D-E as blocks, then use F’s restriction.',140),
  hard('hqr014','Reasoning','Circular seating','Five people P, Q, R, S and T face the centre. Q is second to the right of P. R is immediately left of Q. S is not adjacent to P. Who is immediately right of T?',['P','Q','R','S'],0,'Fix P anywhere. For people facing the centre, right is anticlockwise. Place Q second right of P and R immediately left of Q. S must occupy the only remaining seat not adjacent to P, leaving T beside P. Therefore P is immediately right of T.','Fix one person to remove rotational symmetry and remember the inward-facing direction rule.',130),
  hard('hqr015','Reasoning','Order and sequence','Seven reports P, Q, R, S, T, U and V are reviewed one at a time. R is after P but before T. Q is immediately before U. S is after T. V is before P. Which report must be reviewed before S?',['Only T','P, R and T only','V, P, R and T','Q, U, V, P, R and T'],2,'The forced chain is V before P before R before T before S. Thus V, P, R and T must all precede S. Q and U may lie on either side of S while remaining consecutive.','Build only the relations forced into one chain.',85),
  hard('hqr016','Reasoning','Logical deduction','Four statements are given: (1) If the alarm works, the light flashes. (2) If the light flashes, the guard checks the panel. (3) The guard did not check the panel. (4) The alarm was tested. What follows necessarily?',['The alarm did not work','The alarm was not tested','The light flashed','The guard ignored the light'],0,'From (2), no panel check implies by contraposition that the light did not flash. From (1), no flash implies the alarm did not work. Testing does not imply working.','Apply contraposition backward through the conditional chain.',95),
  hard('hqr017','Reasoning','Input-output','A machine rearranges numbers in successive steps. Input: 42 17 63 28 51. Step 1: 17 42 63 28 51. Step 2: 17 28 42 63 51. Step 3: 17 28 42 51 63. Which rule is used?',['Move the largest remaining number left','Place the smallest remaining number next from the left','Reverse adjacent pairs','Arrange odds before evens'],1,'At each step, the smallest number in the unsorted portion is moved into the next left position: 17 first, then 28, then 42 is already placed, followed by 51. This is a selection-style ascending arrangement.','Watch which value is fixed after each step.',80),
  hard('hqr018','Reasoning','Calendar','If 1 March 2024 was a Friday, what day was 1 March 2025?',['Friday','Saturday','Sunday','Monday'],1,'From 1 March 2024 to 1 March 2025 spans 365 days because the 2024 leap day occurred before the starting date. A 365-day interval shifts the weekday by one, to Saturday.','Check whether 29 February lies inside the interval.',70),
  hard('hqr019','Reasoning','Clock','A clock gains 5 minutes every 3 hours. It is correct at 8:00 a.m. What time will it show when the correct time is 8:00 p.m. the same day?',['8:15 p.m.','8:20 p.m.','8:25 p.m.','8:30 p.m.'],1,'Twelve real hours contain four 3-hour intervals, so the clock gains 4×5=20 minutes. It shows 8:20 p.m.','Count complete three-hour intervals.',55),
  hard('hqr020','Reasoning','Cubes','A cube is painted red on two opposite faces, blue on another pair of opposite faces, and green on the remaining pair. It is cut into 64 equal cubes. How many small cubes have exactly two colours?',['8','16','24','32'],2,'The cube is divided 4×4×4. Cubes with exactly two colours lie on edges but are not corners. There are 12 edges and 4−2=2 such cubes per edge, giving 24.','Count non-corner cubes along all 12 edges.',75),
  hard('hqr021','Reasoning','Venn diagrams','In a group of 120 candidates, 65 study Arithmetic, 55 Reasoning and 50 General Studies. Twenty-five study Arithmetic and Reasoning, 20 Reasoning and General Studies, 18 Arithmetic and General Studies, and 8 study all three. How many study none?',['3','5','7','9'],1,'By inclusion-exclusion, studying at least one =65+55+50−25−20−18+8=115. Therefore 120−115=5 study none.','Use inclusion-exclusion and add the triple overlap back once.',100),
  hard('hqr022','Reasoning','Binary logic','P, Q and R each make one statement. P: “Q is lying.” Q: “R is lying.” R: “P and Q are both truthful.” How many are truthful?',['0','1','2','3'],1,'If R were truthful, P and Q would both be truthful, but P and Q make opposite claims about Q/R, creating a contradiction. Hence R lies. Q’s statement is then true, and P’s statement is false. Exactly one person, Q, is truthful.','Translate each statement into a truth relation.',140),
  hard('hqr023','Reasoning','Cause and effect','Statements: I. Overnight temperature fell below freezing. II. Water in several uncovered roadside containers was frozen by morning.',['I is the cause and II is the effect','II is the cause and I is the effect','Both are independent causes','Both are effects of an unstated cause'],0,'A below-freezing temperature can directly cause exposed water to freeze, so I is a plausible cause and II its effect.','Check temporal order and a direct physical link.',50),
  hard('hqr024','Reasoning','Data sufficiency','Is integer n divisible by 12? I. n is divisible by 3 and 8. II. n is divisible by 4 and 6.',['I alone sufficient','II alone sufficient','Either statement alone sufficient','Both together required'],2,'I gives divisibility by LCM(3,8)=24, hence by 12. II gives divisibility by LCM(4,6)=12. Each statement alone is sufficient.','Take the LCM of the stated divisors.',65),
]
